package rules.fuelConsumption;

import com.ftn.model.events.CurrentSpeedEvent
import com.ftn.model.events.FuelFlowEvent

rule "Immediate fuel consumption"
    lock-on-active
    when
        $afc: Double() from accumulate(
            FuelFlowEvent($immediateConsumption:fuelMiligrams)                  // mg/s
            over window: time(5s), average($immediateConsumption)
        )
        $as: Double(doubleValue > 0) from accumulate(
            CurrentSpeedEvent($speed: currentSpeed)                             // km/h
            over window: time(5s), average($speed)
        )
        $consumption : Double() from ($afc / $as) * 1.32 * 3600 / 10                  // 1.32 * 1 mg/s = 1 ml/s for gasoline
                                                                                // 1 ml/s * 60 * 60 = 1 ml/h
                                                                                //
                                                                                    //
                                                                                //==> 1 ml/h / 10 = 1 L/100km
    then
        System.out.println("Average immediate consumption " + $consumption);    // L/100km
end
